const gulp = require('gulp')

//Очистка папки build перед заданием
const GulpClean = require('gulp-clean')

const buildCleanFunction = function () {
  return gulp.src('./build/*', {read: false})
  .pipe(GulpClean())
}

//Pug2html
const pug = require('gulp-pug')
const htmlBeautify = require('gulp-html-beautify')
const htmlmin = require('gulp-htmlmin')

const pugfunction = function pug2html(cb) {
  var htmlBeautifyOptions = {
    "indent_size": 2
  };
  var htmlminOptions = {
    collapseWhitespace: true,
    includeAutoGeneratedTags: false
  }
  return gulp.src(['./src/*.pug', '!./src/common.pug'])
    .pipe(pug())
    .pipe(htmlmin(htmlminOptions))
    .pipe(htmlBeautify(htmlBeautifyOptions))
    .pipe(gulp.dest('./build'))
}
//Sass function
const sass = require('gulp-sass')
sass.compiler = require('node-sass')
const autoprefixer = require('autoprefixer')
const postcss = require('gulp-postcss')
const sortMediaQueries = require('postcss-sort-media-queries')

const sassfunction = function () {
  var processors = [
    autoprefixer(),
    sortMediaQueries({
      sort: 'mobile-first'
    })
  ]
  return gulp.src('src/*.sass')
    .pipe(sass({outputStyle: 'expanded'}).on('error', sass.logError))
    .pipe(postcss(processors))
    .pipe(gulp.dest('./build/css/'));
}
//JS function
const jsfunction = function(){
  return gulp.src(['./src/**/*.js', '!./src/**/includes/**/*', '!./src/thirdparty/**/*'])
    .pipe(gulp.dest('./build/js/'));
}
//PHP function
const phpfunction = function(){
  return gulp.src(['./src/**/*.php', '!./src/**/includes/**/*', '!./src/thirdparty/**/*'])
    .pipe(gulp.dest('./build/php/'));
}
//Если будут самодельные svg-спрайты, лучше ещё раз всё проверить и сделать их
const makeSvgSymbolSprite = require('./makeSvgSymbolSprite')
module.exports.makeSvgSymbolSprite = makeSvgSymbolSprite
//Копируем спрайт в build
const copySvgSprite = function(){
  return gulp.src('./src/common/svg-sprite/*')
    .pipe(gulp.dest('./build/img/common/svg-sprite/'));
}
//Оптимизация и копирование картинок
const imagemin = require('gulp-imagemin')
const imgCompress = require('imagemin-jpeg-recompress')
const cache = require('gulp-cache');

const imgfunction = function () {
  return gulp.src(['./src/**/*.svg', './src/**/*.jpg', './src/**/*.png', './src/**/*.gif', '!./src/**/includes/**/*', '!./src/common/svg-sprite/*'])
    .pipe(
      cache(
        imagemin([
          imgCompress({
            loops: 4,
            min: 75,
            max: 80,
            quality: 'high'
          }),
          imagemin.gifsicle(),
          imagemin.optipng(),
          imagemin.svgo()
        ])
      )
    )
    .pipe(gulp.dest('build/img/'));
}
//Копирование шрифтов
const copyfontsfunction = function () {
  return gulp.src('./src/common/fonts/*.woff*')
    .pipe(gulp.dest('./build/fonts/'));
}
//Копирование сторонних скриптов
const copythirdpartyfunction = function () {
  return gulp.src('./src/thirdparty/**/*')
    .pipe(gulp.dest('./build/thirdparty/'));
}

//Live server - проверим результат в браузере
const browsersync = require('browser-sync')
const liveserver = function bsync() {
  browsersync.init({
    watch: true,
    server: {
      baseDir: "./build/",
    }
  })
}

//Final task
const build = gulp.series(buildCleanFunction, pugfunction, sassfunction, jsfunction, phpfunction, makeSvgSymbolSprite, copySvgSprite, imgfunction, copyfontsfunction, copythirdpartyfunction, liveserver)

module.exports = gulp.series(build)