const gulp = require('gulp');
const gulpClean = require('gulp-clean'); //Очистка
const replace = require('gulp-replace'); //Замена
const rename = require('gulp-rename'); //Переименование

//Очистка папки build перед заданием
const buildCleanFunction = function () {
  return gulp.src('./build/*', { read: false })
    .pipe(gulpClean());
}

//2html
const fileinclude = require('gulp-file-include');
const htmlmin = require('gulp-htmlmin');
const posthtml = require('gulp-posthtml');
const posthtmlWebpWidthSizes = require('../posthtml/posthtmlWebpWidthSizes');
const htmlminOptions = {
  collapseWhitespace: true,
  includeAutoGeneratedTags: false,
  removeComments: true,
  collapseBooleanAttributes: true,
  preserveLineBreaks: true
}
const htmlfunction = function pug2html(cb) {
  var cacheTimeStamp = new Date().getTime();
  return gulp.src(['./src/**/index.html', '!./src/components/**', '!./src/third-party/**'])
    .pipe(fileinclude({
      prefix: '@@',
      basepath: '@file'
    }))
    .pipe(posthtml([posthtmlWebpWidthSizes()]))
    .pipe(replace('style.css', 'style-min.css?t=' + cacheTimeStamp))
    .pipe(replace('script.js', 'script-min.js?t=' + cacheTimeStamp))
    .pipe(htmlmin(htmlminOptions))
    .pipe(gulp.dest('./build/'));
}
//CSS function
const autoprefixer = require('autoprefixer')
const postcss = require('gulp-postcss')
const sortMediaQueries = require('postcss-sort-media-queries')
const cssmin = require('gulp-cssmin')
const processors = [
  autoprefixer(),
  sortMediaQueries({
    sort: 'mobile-first'
  })
]

const cssfunction = function () {
  return gulp.src(['./src/**/style.css', '!./src/components/**', '!./src/third-party/**'])
    .pipe(fileinclude({
      prefix: '@@',
      basepath: '@file'
    }))
    .pipe(postcss(processors))
    .pipe(cssmin())
    .pipe(rename(function (path) { path.basename += "-min" }))
    .pipe(gulp.dest('./build/'));
}

//JS function
//Функция сборщик скриптов страницы из build-script.pug в script.js, если требуется
const buildCustomStyle = function () {
  return gulp.src(['./src/**/build-script.js', '!./src/components/**', '!./src/third-party/**'])
    .pipe(fileinclude({
      prefix: '@@',
      basepath: '@file'
    }))
    .pipe(rename(function (path) {
      path.basename = 'script';
      path.extname = '.js'
    }))
    .pipe(minify())
    .pipe(gulp.dest('./build/'));
}
const minify = require('gulp-minify');
//Если скрипт небольшой минуем этап сборки и пишем сразу в script.js
const jsMinFunction = function () {
  return gulp.src(['./src/**/script.js', '!./src/components/**', '!./src/third-party/**'])
    .pipe(minify())
    .pipe(gulp.dest('./build/'));
}
//Удаляем жирный JS
const cleanJsFunction = function () {
  return gulp.src(['./build/**/script.js'], { read: false })
    .pipe(gulpClean());
}
//Создаём серию
const jsfunction = gulp.series(buildCustomStyle, jsMinFunction, cleanJsFunction);

//PHP function
const phpfunction = function () {
  return gulp.src(['./src/**/*.php', '!./src/components/**', '!./src/third-party/**'])
    .pipe(gulp.dest('./build/'));
}
//Оптимизация и копирование картинок
const imagemin = require('gulp-imagemin');
const imgCompress = require('imagemin-jpeg-recompress');
const cache = require('gulp-cache');

const imgMinFunction = function () {
  return gulp.src(['./src/**/*.svg', './src/**/*.jpg', './src/**/*.png', './src/**/*.gif', '!./src/components/**', '!./src/third-party/**'])
    .pipe(
      cache(
        imagemin([
          imgCompress({
            loops: 4,
            min: 70,
            max: 75,
            quality: 'high'
          }),
          imagemin.gifsicle(),
          imagemin.optipng(),
          imagemin.svgo()
        ])
      )
    )
    .pipe(gulp.dest('build/'));
}
const webp = require('gulp-webp');
const webpFunction = function (input, output) {
  return gulp.src(['src/**/*.png', 'src/**/*.jpg', 'src/**/*.gif', '!./src/components/**', '!./src/third-party/**'])
    .pipe(webp())
    .pipe(gulp.dest('build/'));
}
const imgfunction = gulp.series(imgMinFunction, webpFunction);
//Копирование шрифтов
const copyfontsfunction = function () {
  return gulp.src('./src/common/fonts/*.woff*')
    .pipe(gulp.dest('./build/common/fonts/'));
}
//Копирование сторонних скриптов
const copyThirdPartyFunction = function () {
  return gulp.src('./src/third-party/**')
    .pipe(gulp.dest('./build/third-party/'));
}

//Live server - проверим результат в браузере
const browsersync = require('browser-sync')
const liveserver = function bsync() {
  browsersync.init({
    watch: true,
    server: {
      baseDir: "./build/",
    }
  })
}

//Final task
const stdbuild = gulp.series(buildCleanFunction, htmlfunction, cssfunction, jsfunction, phpfunction, imgfunction, copyfontsfunction, copyThirdPartyFunction, liveserver)

module.exports = gulp.series(stdbuild)